export enum TypographyConst {
  flow_title = "flow-title",
  title_mega_title = "title-mega-title",
  title_title = "title-title",
  title_subtitle = "title-subtitle",
  title_header = "title-header",
  title_subhead = "title-subhead",
  body_body_bold = "body-body-bold",
  body_body_strong = "body-body-strong",
  body_body_regular = "body-body-regular",
  body_medium_regular = "body-medium-regular",
  body_medium_underlined = "body-medium-underlined",
  body_medium_strong = "body-medium-strong",
  body_medium_bold = "body-medium-bold",
  body_small_regular = "body-small-regular",
  body_small_regular_underlined = "body-small-regular-underlined",
  body_small_strong = "body-small-strong",
  body_small_graph_legend = "body-small-graph-legend",
  body_label = "body-label",
  body_overline = "body-overline",
  body_overline_strong = "body-overline-strong"
}
